name: dffdf
on: 
  workflow_dispatch:
   inputs:
     auth:
        description: 'GRDP Authorization Code'
        required: true
        
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Creating User to Login
      run: |
         sudo useradd -m Area69Lab && sudo adduser Area69Lab sudo && echo 'Area69Lab:Area69Lab' | sudo chpasswd
    - name: Installing Desktop Environment (wait for 10 min)
      run: sudo apt update && sudo apt install ubuntu-desktop
    - name: Installing Google Chrome Headless
      run: |
           wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
           sudo dpkg --install google-chrome-stable_current_amd64.deb
           sudo apt install --assume-yes --fix-broken
    - name: Installing Some Configurations
      run: |
           sudo apt install nautilus expect nano pavucontrol vlc -y
           sudo apt install --assume-yes xscreensaver
    - name: Installing tg
      run: |
           wget -O- https://telegram.org/dl/desktop/linux | sudo tar xJ -C /opt/
    - name: Adding tg to path
      run: |
           sudo ln -s /opt/Telegram/Telegram /usr/local/bin/telegram-desktop
    - name: Installing Grdp
      run: |
           sudo apt-get update
           sudo apt-get install xbase-clients python3-psutil xvfb -y
           wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
           sudo dpkg --install chrome-remote-desktop_current_amd64.deb
           sudo apt install --assume-yes --fix-broken
    - name: generate script
      run: |
           touch setup.sh
           echo "${{ github.event.inputs.auth }}" >> "setup.sh"
           chmod 777 setup.sh
    - name: initialize GRDP
      run: |   
           expect -c '
           spawn ./setup.sh
           expect "Enter a PIN of at least six digits: "
           send "123456\r"
           expect "Enter the same PIN again: "
           send "123456\r"
           expect eof
           '
    - name: Sleep for 30 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '400m'
